sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating on image with dockefile"
  - docker build -t ykh815/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true ykh815/docker-react-app npm run test -- --coverage

after_success: 
  - echo "Test Success"
